#!/usr/bin/env ruby

require "bundler/setup"
require "r-fxxk"

class Nana < Brainfuck
  inc "ミミミン" # +
  dec "！" # -
  opn "ウサウサウーサ" # [
  cls "ウーサミン" # ]
  nxt "ウサミン" # >
  prv "ナナー" # <
  put "うードッカーン" # .
  get "メルヘンチェーンジ" # ,
end

puts Nana.new.fuck(ARGF.read)
